import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dekamond Task",
  description: "Client Auth Project Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        <section className=" bg-gray-300 text-gray-900 min-h-screen flex items-center justify-center">
          {children}
        </section>
      </body>
    </html>
  );
}
